apiVersion: 1

datasources:
  - name: Fuel Log API
    type: yesoreyeram-infinity-datasource
    uid: fuel-log-api
    access: proxy
    isDefault: true
    jsonData:
      global_queries: []
    editable: true
